# Generated by Django 4.0.4 on 2023-11-14 22:06

import chatapi.models.models
from django.db import migrations, models
import enumchoicefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NtChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=16)),
                ('thread_id', models.IntegerField(default=0)),
                ('sequential_order', models.IntegerField(default=0)),
                ('role', models.CharField(default='user', max_length=16)),
                ('content', models.TextField(default=None)),
                ('status', enumchoicefield.fields.EnumChoiceField(default=chatapi.models.models.MessageStatus(1), enum_class=chatapi.models.models.MessageStatus, max_length=14)),
            ],
        ),
    ]
